digirati-co-uk/timeliner

- src/components/IIIFAvProvider/IIIFAvProvider.js
- src/components/IIIFAvProvider/IIIFAvProvider.mdx
This proof of concept has some commented out code. It experiments with Audio "voting" on what the correct timestamp is and the main clock correcting based on this. Some code duplication with the scrubber, but this is all POC work.
> Rough proof of concept AV Provider and audio syncing

- package.json
- src/components/CurrentTimeIndicator/CurrentTimeIndicator.js
- src/components/CurrentTimeIndicator/CurrentTimeIndicator.mdx
- src/components/CurrentTimeIndicator/CurrentTimeIndicator.scss
- yarn.lock
Added current time indicator component,  closes #47
> Current time indicator

- src/components/AudioTransportBar/AudioTransportBar.js
- src/components/CurrentTimeIndicator/CurrentTimeIndicator.scss
- src/components/NextButton/NextButton.js
- src/components/NextButton/NextButton.mdx
- src/components/PlayPauseButton/PlayPauseButton.js
- src/components/PlayPauseButton/PlayPauseButton.mdx
- src/components/PreviousButton/PreviousButton.js
- src/components/PreviousButton/PreviousButton.mdx
- src/components/SkipAheadButton/SkipAheadButton.js
- src/components/SkipAheadButton/SkipAheadButton.mdx
- src/components/SkipBackwardsButton/SkipBackwardsButton.js
- src/components/SkipBackwardsButton/SkipBackwardsButton.mdx
- src/components/TransportBarButton/TransportBarButton.scss
#41 - Dual state Play/Pause Button
#42 #43 - Next And Previous Bubble buttons 
#44 #45 - Skip buttons
Also fixed the padding on current time indicator
edit, automation:
closes #41
closes #42
closes #43
closes #44
closes #45
> Added transport bar buttons ui and demos

- src/components/BubbleDisplay/BubbleDisplay.DemoPoints.js
- src/components/BubbleDisplay/BubbleDisplay.js
- src/components/BubbleDisplay/BubbleDisplay.mdx
- src/components/SingleBubble/SingleBubble.js
- src/components/SingleBubble/SingleBubble.mdx
closes #31 and closes #29 
edit: automation
> SVG Based Bubble Display Component

- src/components/AudioImporter/AudioImporter.ManifestTemplate.js
- src/components/AudioImporter/AudioImporter.Utils.js
- src/components/AudioImporter/AudioImporter.js
- src/components/AudioImporter/AudioImporter.mdx
- src/components/AudioImporter/AudioImporter.scss
> Created audio importer ui

- package.json
- src/components/KeyboardControlsProvider/KeyboardControlsProvder.mdx
- src/components/KeyboardControlsProvider/KeyboardControlsProvider.js
- src/components/KeyboardControlsProvider/KeyboardControlsProvider.mdx
- yarn.lock
> added keyboard controls provider

- src/components/docs/technical-documentation/iiif-output.mdx
Example IIIF Output for the timeliner
> IIIF output example

- src/utils/iiifSaver.js
- src/utils/iiifSerializer.js
Summary was missing from the key order, and the export has some improvements.
> Fixed manifest serialisation issues

- src/containers/VariationsMainView/VariationsMainView.js
> split at current time instead of half of the seleced

- src/containers/BubbleEditor/BubbleEditor.js
> last marker draggability removed

- src/components/Playhead/Playhead.scss
> playhead indicator added

- src/utils/iiifLoader.js
- src/utils/iiifSaver.js
> manifest title/description serialisation fixed

- src/utils/iiifLoader.js
> fixed bacground colour persistance

- src/components/BubbleDisplay/BubbleDisplay.js
- src/components/SingleBubble/SingleBubble.js
> parent bubble always contains the child

- src/actions/canvas.js
- src/constants/canvas.js
- src/reducers/canvas.js
- src/sagas/index.js
> fixed bug when the different project loaded with same audio

- src/components/AudioImporter/AudioImporter.js
- src/store/main.js
Some updates to the redux store too, it was not working.
> Closes #186 fixes the name on the input field

- package.json
- src/containers/Root/Root.js
- src/index.js
- src/store/main.js
- yarn.lock
QoL to speed up development: keeps the state when you refresh the page. Can still reset using the buttons inline
> Added local storage persistence

- src/containers/BubbleEditor/BubbleEditor.js
Reverts digirati-co-uk/timeliner#211
> Revert "Bubble editor, resizing interactive"

- src/components/AudioTransportBar/AudioTransportBar.scss
- src/components/BubbleDisplay/BubbleDisplay.js
- src/components/SettingsPopoup/SettingsPopup.js
- src/components/TimelineScrubber/TimelineScrubber.js
- src/constants/project.js
- src/containers/BubbleEditor/BubbleEditor.js
> Added background colour switch

- src/components/ColourSwatchPicker/ColourSwatchPicker.js
> Added dismiss to colour picker

- src/components/AudioImporter/AudioImporter.js
- src/components/FileUpload/FileUpload.js
- src/components/FileUpload/FileUpload.mdx
- src/components/FileUpload/FileUpload.scss
> Added file upload option

- src/actions/range.js
- src/components/BubbleDisplay/BubbleDisplay.js
- src/components/MetadataEditor/MetadataEditor.js
- src/constants/range.js
- src/reducers/range.js
- src/utils/iiifLoader.js
- src/utils/iiifSaver.js
- src/utils/iiifSerializer.js
> Added tooltip colour option on ranges

- package.json
- src/components/Metadata/Metadata.js
- yarn.lock
Clearer way to show when an annotation has changed.
> Annotation animation

- src/actions/canvas.js
- src/components/BubbleDisplay/BubbleDisplay.js
- src/components/Metadata/Metadata.js
- src/reducers/range.js
- src/store/undo.js
- src/utils/iiifSaver.js
Fixed #259 exporting now shows ranges
> Exporting now shows ranges

- src/components/VariationsAppBar/VariationsAppBar.js
Co-authored-by: Brian Keese bkeese@indiana.edu
Co-authored-by: Dananji Withana dwithana@iu.edu
> Remove useless close button

- src/sagas/index.js
> Fixed bug where image would jump past the end

- src/components/AudioImporter/AudioImporter.Utils.js
- src/components/AudioImporter/AudioImporter.js
- src/components/FileUpload/FileUpload.js
> Extended file validation

- src/components/MarkerMetadata/MarkerMetadata.js
- src/components/Metadata/Metadata.scss
- src/components/MetadataEditor/MetadataEditor.js
- src/components/ProjectMetadataEditor/ProjectMetadataEditor.js
- src/containers/VariationsMainView/VariationsMainView.scss
- src/main.scss
> Fixed firefox flexbox bug (flex: 1 -> flex: 1 1 0)

- src/components/BubbleDisplay/BubbleDisplay.scss
- src/components/SingleBubble/SingleBubble.js
- src/components/TimelineScrubber/TimelineScrubber.js
- src/components/TimelineScrubber/TimelineScrubber.scss
> Fixed transitions when zooming in and out

- src/components/MetadataEditor/MetadataEditor.js
> Fixed colours bug
